/* Seed data for the migration tool */

const TENANT = 'KDB Bank';

const PROJECTS = [
  { id: 'p1', name: 'Core Ledger',          client: TENANT, tables: 142, status: 'running', src: 'Mainframe (EBCDIC)', tgt: 'PostgreSQL 15',  updated: '2 min ago' },
  { id: 'p2', name: 'Deposit Accounts',     client: TENANT, tables: 87,  status: 'running', src: 'Oracle 11g',         tgt: 'PostgreSQL 15',  updated: '8 min ago' },
  { id: 'p3', name: 'FX Treasury',          client: TENANT, tables: 34,  status: 'waiting', src: 'Mainframe (EBCDIC)', tgt: 'Linux / UTF-8',  updated: '1 hr ago' },
  { id: 'p4', name: 'Loan Origination',     client: TENANT, tables: 61,  status: 'waiting', src: 'Oracle 12c',         tgt: 'PostgreSQL 15',  updated: '3 hr ago' },
  { id: 'p5', name: 'Card Authorization',   client: TENANT, tables: 28,  status: 'done',    src: 'Mainframe (EBCDIC)', tgt: 'PostgreSQL 14',  updated: 'Mar 14' },
  { id: 'p6', name: 'GL Consolidation',     client: TENANT, tables: 113, status: 'done',    src: 'Oracle 11g',         tgt: 'PostgreSQL 15',  updated: 'Feb 28' },
  { id: 'p7', name: 'Trade Finance',        client: TENANT, tables: 19,  status: 'done',    src: 'Mainframe (EBCDIC)', tgt: 'Linux / UTF-8',  updated: 'Feb 02' },
];

/* Dashboard tables */
const TABLES = [
  { name: 'ACCT_MASTER',        rows: 18_442_331, done: 18_442_331, pct: 100, status: 'ok',      rule: 42, issues: 0,  updated: '09:41:02', schema: 'PROD_CORE' },
  { name: 'TXN_JOURNAL_2023',   rows: 284_003_117, done: 201_554_440, pct: 70.9, status: 'running', rule: 87, issues: 2,  updated: '09:41:08', schema: 'PROD_CORE' },
  { name: 'TXN_JOURNAL_2024',   rows: 312_889_001, done: 218_995_337, pct: 70.0, status: 'running', rule: 87, issues: 0,  updated: '09:41:08', schema: 'PROD_CORE' },
  { name: 'CUST_PROFILE',       rows: 2_118_774,  done: 2_118_774, pct: 100, status: 'ok',      rule: 31, issues: 0,  updated: '09:12:41', schema: 'PROD_CORE' },
  { name: 'CUST_CONTACT',       rows: 4_882_091,  done: 4_882_091, pct: 100, status: 'ok',      rule: 14, issues: 0,  updated: '09:14:03', schema: 'PROD_CORE' },
  { name: 'ADDR_HIST',          rows: 9_014_220,  done: 6_102_334, pct: 67.7, status: 'running', rule: 9,  issues: 0,  updated: '09:41:01', schema: 'PROD_CORE' },
  { name: 'KYC_DOCUMENT',       rows: 1_204_553,  done: 0,          pct: 0,   status: 'blocked', rule: 23, issues: 1,  updated: '09:02:18', schema: 'PROD_RISK' },
  { name: 'LOAN_APPLICATION',   rows: 884_112,    done: 884_112,    pct: 100, status: 'ok',      rule: 55, issues: 0,  updated: '08:54:22', schema: 'PROD_LOAN' },
  { name: 'LOAN_DISBURSEMENT',  rows: 612_004,    done: 612_004,    pct: 100, status: 'ok',      rule: 48, issues: 0,  updated: '08:57:10', schema: 'PROD_LOAN' },
  { name: 'LOAN_REPAYMENT',     rows: 5_412_889,  done: 2_118_332,  pct: 39.1, status: 'running', rule: 48, issues: 0,  updated: '09:41:04', schema: 'PROD_LOAN' },
  { name: 'CARD_MASTER',        rows: 3_002_114,  done: 0,          pct: 0,   status: 'queued',  rule: 17, issues: 0,  updated: '—',        schema: 'PROD_CARD' },
  { name: 'CARD_AUTH_LOG',      rows: 812_004_552, done: 0,         pct: 0,   status: 'queued',  rule: 22, issues: 0,  updated: '—',        schema: 'PROD_CARD' },
  { name: 'FX_RATE_DAILY',      rows: 44_211,     done: 44_211,     pct: 100, status: 'ok',      rule: 6,  issues: 0,  updated: 'yesterday',schema: 'PROD_FX' },
  { name: 'FX_POSITION',        rows: 120_554,    done: 120_554,    pct: 100, status: 'ok',      rule: 11, issues: 0,  updated: 'yesterday',schema: 'PROD_FX' },
  { name: 'GL_BALANCE',         rows: 2_881_009,  done: 2_881_009,  pct: 100, status: 'ok',      rule: 19, issues: 0,  updated: 'yesterday',schema: 'PROD_GL' },
  { name: 'GL_ENTRY',           rows: 98_221_412, done: 51_104_331, pct: 52.0, status: 'warn',    rule: 35, issues: 4,  updated: '09:40:55', schema: 'PROD_GL' },
  { name: 'BRANCH_MASTER',      rows: 1_814,      done: 1_814,      pct: 100, status: 'ok',      rule: 8,  issues: 0,  updated: 'Mar 30',  schema: 'PROD_ORG' },
  { name: 'EMPLOYEE',           rows: 22_104,     done: 22_104,     pct: 100, status: 'ok',      rule: 12, issues: 0,  updated: 'Mar 30',  schema: 'PROD_ORG' },
];

/* Mapping rows (source → target) */
const MAPPING = [
  { src: 'ACCT-NO',           srcType: 'CHAR(16)',      tgt: 'account_no',          tgtType: 'VARCHAR(16)',   rule: 'auto', status: 'ok',   pk: true,  note: '' },
  { src: 'CUST-ID',           srcType: 'CHAR(10)',      tgt: 'customer_id',         tgtType: 'VARCHAR(10)',   rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'BR-CODE',           srcType: 'CHAR(4)',       tgt: 'branch_code',         tgtType: 'CHAR(4)',       rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'ACCT-TYPE',         srcType: 'CHAR(2)',       tgt: 'account_type',        tgtType: 'SMALLINT',      rule: 'rule', status: 'ok',   pk: false, note: 'LOOKUP(acct_type_dict)' },
  { src: 'CURRENCY-CD',       srcType: 'CHAR(3)',       tgt: 'currency_code',       tgtType: 'CHAR(3)',       rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'BAL-AMT',           srcType: 'COMP-3 S9(13)V99', tgt: 'balance_amount',   tgtType: 'NUMERIC(15,2)', rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'AVAIL-AMT',         srcType: 'COMP-3 S9(13)V99', tgt: 'available_amount', tgtType: 'NUMERIC(15,2)', rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'HOLD-AMT',          srcType: 'COMP-3 S9(13)V99', tgt: 'hold_amount',      tgtType: 'NUMERIC(15,2)', rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'OPEN-DT',           srcType: 'CHAR(8) YYYYMMDD', tgt: 'opened_at',        tgtType: 'DATE',          rule: 'rule', status: 'ok',   pk: false, note: 'TO_DATE(?, \'YYYYMMDD\')' },
  { src: 'LAST-TXN-TS',       srcType: 'CHAR(14)',      tgt: 'last_txn_at',         tgtType: 'TIMESTAMP',     rule: 'rule', status: 'warn', pk: false, note: 'NULLIF(\'00000000000000\')' },
  { src: 'STATUS-FLG',        srcType: 'CHAR(1)',       tgt: 'status',              tgtType: 'VARCHAR(12)',   rule: 'rule', status: 'ok',   pk: false, note: "MAP A→'ACTIVE', C→'CLOSED', D→'DORMANT'" },
  { src: 'RISK-SCORE',        srcType: 'COMP S9(4)',    tgt: 'risk_score',          tgtType: 'SMALLINT',      rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'KYC-LEVEL',         srcType: 'CHAR(1)',       tgt: 'kyc_level',           tgtType: 'SMALLINT',      rule: 'rule', status: 'ok',   pk: false, note: 'CAST' },
  { src: 'ACCT-NAME-KANJI',   srcType: 'CHAR(40) EBCDIC-KANA', tgt: 'account_name', tgtType: 'VARCHAR(80)',   rule: 'rule', status: 'warn', pk: false, note: 'ICONV ebcdic-kana → utf-8' },
  { src: 'ACCT-NAME-KANA',    srcType: 'CHAR(40) EBCDIC-KANA', tgt: 'account_name_kana', tgtType: 'VARCHAR(80)', rule: 'rule', status: 'ok', pk: false, note: 'ICONV ebcdic-kana → utf-8' },
  { src: 'PRODUCT-CD',        srcType: 'CHAR(6)',       tgt: 'product_code',        tgtType: 'VARCHAR(6)',    rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'OFFICER-ID',        srcType: 'CHAR(8)',       tgt: 'officer_id',          tgtType: 'VARCHAR(8)',    rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'INTEREST-RT',       srcType: 'COMP-3 S9(3)V9(6)', tgt: 'interest_rate',   tgtType: 'NUMERIC(9,6)',  rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'FILLER-01',         srcType: 'CHAR(20)',      tgt: '—',                   tgtType: '—',             rule: 'skip', status: 'skip', pk: false, note: 'padding, discard' },
  { src: 'RSRV-FLAG',         srcType: 'CHAR(1)',       tgt: '—',                   tgtType: '—',             rule: 'skip', status: 'skip', pk: false, note: 'reserved, legacy' },
  { src: 'UPD-USER',          srcType: 'CHAR(8)',       tgt: 'updated_by',          tgtType: 'VARCHAR(8)',    rule: 'auto', status: 'ok',   pk: false, note: '' },
  { src: 'UPD-TS',            srcType: 'CHAR(14)',      tgt: 'updated_at',          tgtType: 'TIMESTAMP',     rule: 'rule', status: 'err',  pk: false, note: 'invalid in 1,204 rows — recovery required' },
  { src: '—',                 srcType: '—',             tgt: 'tenant_id',           tgtType: 'UUID',          rule: 'added', status: 'ok',  pk: false, note: 'no AS-IS source · default = gen_random_uuid()' },
  { src: '—',                 srcType: '—',             tgt: 'created_at',          tgtType: 'TIMESTAMPTZ',   rule: 'added', status: 'ok',  pk: false, note: 'no AS-IS source · default = now()' },
  { src: '—',                 srcType: '—',             tgt: 'data_classification', tgtType: 'VARCHAR(16)',   rule: 'added', status: 'warn', pk: false, note: 'no AS-IS source · default literal required before run' },
];

/* Execution pipeline stages */
const STAGES = [
  { id: 'extract',  name: 'Extract',            sub: 'read EBCDIC dataset',      pct: 100, tone: 'ok',      rate: '—',        eta: 'done',   color: '#3b82a6' },
  { id: 'encode',   name: 'Character encode',   sub: 'EBCDIC → UTF-8',           pct: 100, tone: 'ok',      rate: '—',        eta: 'done',   color: '#6b7fb0' },
  { id: 'unpack',   name: 'Unpack',             sub: 'COMP-3 → NUMERIC',         pct: 82,  tone: 'running', rate: '412 MB/s', eta: '04:12',  color: '#8b6fb0' },
  { id: 'transform',name: 'Transform',          sub: 'rules · lookups',          pct: 61,  tone: 'running', rate: '298 MB/s', eta: '07:45',  color: '#b06f9f' },
  { id: 'validate', name: 'Validate',           sub: 'PK · FK · constraints',    pct: 34,  tone: 'running', rate: '184 MB/s', eta: '12:03',  color: '#b08a6f' },
  { id: 'load',     name: 'Load',               sub: 'COPY → PostgreSQL',        pct: 12,  tone: 'running', rate: '142 MB/s', eta: '28:40',  color: '#6fa07a' },
  { id: 'verify',   name: 'Verify',             sub: 'row count · checksum',     pct: 0,   tone: 'idle',    rate: '—',        eta: 'queued', color: '#8892a0' },
];

/* Log lines */
const LOG_LINES = [
  ['09:41:08.221','INFO', 'loader.copy',  'LOAD  TXN_JOURNAL_2024  rows=50000  elapsed=312ms'],
  ['09:41:08.118','INFO', 'loader.copy',  'LOAD  TXN_JOURNAL_2023  rows=50000  elapsed=298ms'],
  ['09:41:07.994','OK',   'verify.chk',   'CHECKSUM ok  ACCT_MASTER  sha256=8a2c..e109  rows=18442331'],
  ['09:41:07.831','INFO', 'transform',    'rule.apply  status_flg_map  in=50000  out=50000  skipped=0'],
  ['09:41:07.712','WARN', 'transform',    'last_txn_ts  null-coerced rows=14  table=TXN_JOURNAL_2024'],
  ['09:41:07.441','INFO', 'encode',       'iconv  ebcdic-kana → utf-8  buffer=64MB  throughput=412MB/s'],
  ['09:41:07.312','INFO', 'extract',      'read  /vol/mf/TXN_JOURNAL_2024.dat  offset=0x2A81FF00  chunk=256MB'],
  ['09:41:06.998','ERROR','validate.fk',  'FK violation  GL_ENTRY.acct_no → ACCT_MASTER.account_no  rows=4  first=AC00881104'],
  ['09:41:06.741','INFO', 'loader.stage', 'stage.flush  ADDR_HIST  pending=0  committed=6102334'],
  ['09:41:06.512','OK',   'verify.chk',   'CHECKSUM ok  CUST_CONTACT  sha256=91ff..2b40  rows=4882091'],
  ['09:41:06.331','INFO', 'transform',    'rule.apply  to_date(yyyymmdd)  in=50000  out=49997  skipped=3'],
  ['09:41:06.114','WARN', 'unpack',       'COMP-3  sign nibble unexpected 0xF  col=BAL_AMT  row=2118441  coerced→positive'],
  ['09:41:05.881','INFO', 'loader.copy',  'LOAD  LOAN_REPAYMENT  rows=50000  elapsed=341ms'],
  ['09:41:05.710','INFO', 'extract',      'read  /vol/mf/TXN_JOURNAL_2023.dat  offset=0x1F04A100  chunk=256MB'],
  ['09:41:05.441','ERROR','encode',       'invalid EBCDIC byte 0x3F at offset 0x1A08B2C  table=KYC_DOCUMENT  aborting'],
  ['09:41:05.221','INFO', 'scheduler',    'worker pool: 12 active / 16 total · queue depth=3'],
  ['09:41:04.998','OK',   'verify.chk',   'CHECKSUM ok  FX_POSITION  sha256=2d18..07aa  rows=120554'],
  ['09:41:04.774','INFO', 'transform',    'rule.apply  currency_cd_norm  in=50000  out=50000'],
  ['09:41:04.551','INFO', 'loader.stage', 'stage.flush  LOAN_REPAYMENT  pending=0  committed=2118332'],
  ['09:41:04.331','WARN', 'transform',    'account_name  kanji codepoint outside JIS X 0208  fallback U+FFFD  rows=2'],
  ['09:41:04.118','INFO', 'extract',      'mount OK  /vol/mf  dataset=KSDS  rlen=512  blksz=27648'],
  ['09:41:03.881','INFO', 'loader.copy',  'LOAD  TXN_JOURNAL_2024  rows=50000  elapsed=307ms'],
  ['09:41:03.714','OK',   'verify.chk',   'CHECKSUM ok  GL_BALANCE  sha256=5b71..c902  rows=2881009'],
  ['09:41:03.551','INFO', 'transform',    'rule.apply  status_flg_map  in=50000  out=50000'],
  ['09:41:03.331','INFO', 'encode',       'iconv  ebcdic-kana → utf-8  buffer=64MB  throughput=398MB/s'],
  ['09:41:03.118','INFO', 'scheduler',    'backpressure: loader lag 212ms (threshold 500ms) → OK'],
  ['09:41:02.881','OK',   'verify.chk',   'CHECKSUM ok  ACCT_MASTER  sha256=8a2c..e109  rows=18442331'],
  ['09:41:02.714','INFO', 'loader.copy',  'LOAD  ADDR_HIST  rows=50000  elapsed=288ms'],
  ['09:41:02.551','ERROR','loader.copy',  'duplicate key (account_no)=(AC10023441)  table=ACCT_MASTER  row skipped'],
  ['09:41:02.331','INFO', 'unpack',       'COMP-3 decoder  throughput=524MB/s  rows=1.2M/s'],
  ['09:41:02.118','INFO', 'transform',    'rule.apply  to_date(yyyymmdd)  in=50000  out=49999  skipped=1'],
  ['09:41:01.881','WARN', 'validate.pk',  'PK duplicate soft-dedupe  table=CUST_CONTACT  rows=3'],
  ['09:41:01.714','INFO', 'loader.stage', 'stage.flush  TXN_JOURNAL_2023  pending=0  committed=201554440'],
  ['09:41:01.551','INFO', 'extract',      'read  /vol/mf/ADDR_HIST.dat  offset=0x0C112A00  chunk=128MB'],
  ['09:41:01.331','OK',   'verify.chk',   'CHECKSUM ok  FX_RATE_DAILY  sha256=fa02..9911  rows=44211'],
  ['09:41:01.118','INFO', 'scheduler',    'worker pool: 12 active / 16 total · queue depth=2'],
];

/* ─── Artifacts: schema diff between ASIS (source) and TOBE (target) ──────
   Each table lists ASIS columns + TOBE columns; diff is computed on the fly.
   TOBE columns may carry .default (initial value for newly added columns) and
   .renameFrom (detected rename candidate, possibly .renameConfidence < 1). */

const SCHEMA_DIFF = [
  {
    table: 'ACCT_MASTER',
    asis:  'CORE.ACCT_MASTER',
    tobe:  'public.account',
    asisCols: [
      { name: 'ACCT_NO',      type: 'CHAR(16)',            nullable: false, pk: true  },
      { name: 'CUST_ID',      type: 'CHAR(10)',            nullable: false },
      { name: 'BR_CODE',      type: 'CHAR(4)',             nullable: false },
      { name: 'ACCT_TYPE',    type: 'CHAR(2)',             nullable: false },
      { name: 'CURRENCY_CD',  type: 'CHAR(3)',             nullable: false },
      { name: 'BAL_AMT',      type: 'COMP-3 S9(13)V99',    nullable: false },
      { name: 'OPEN_DT',      type: 'CHAR(8) YYYYMMDD',    nullable: false },
      { name: 'STATUS_FLG',   type: 'CHAR(1)',             nullable: false },
      { name: 'ACCT_NAME_KANJI', type: 'CHAR(40) EBCDIC-KANA', nullable: true },
      { name: 'FILLER_01',    type: 'CHAR(20)',            nullable: true },
      { name: 'RSRV_FLAG',    type: 'CHAR(1)',             nullable: true },
      { name: 'UPD_USER',     type: 'CHAR(8)',             nullable: true },
      { name: 'UPD_TS',       type: 'CHAR(14)',            nullable: true },
    ],
    tobeCols: [
      { name: 'account_no',       type: 'VARCHAR(16)',     nullable: false, pk: true, renameFrom: 'ACCT_NO',     renameConfidence: 1.00 },
      { name: 'customer_id',      type: 'VARCHAR(10)',     nullable: false,           renameFrom: 'CUST_ID',     renameConfidence: 1.00 },
      { name: 'branch_code',      type: 'CHAR(4)',         nullable: false,           renameFrom: 'BR_CODE',     renameConfidence: 0.95 },
      { name: 'account_type',     type: 'SMALLINT',        nullable: false,           renameFrom: 'ACCT_TYPE',   renameConfidence: 1.00 },
      { name: 'currency_code',    type: 'CHAR(3)',         nullable: false,           renameFrom: 'CURRENCY_CD', renameConfidence: 1.00 },
      { name: 'balance_amount',   type: 'NUMERIC(15,2)',   nullable: false,           renameFrom: 'BAL_AMT',     renameConfidence: 0.92 },
      { name: 'opened_at',        type: 'DATE',            nullable: false,           renameFrom: 'OPEN_DT',     renameConfidence: 0.88 },
      { name: 'status',           type: 'VARCHAR(12)',     nullable: false,           renameFrom: 'STATUS_FLG',  renameConfidence: 0.70 },
      { name: 'account_name',     type: 'VARCHAR(80)',     nullable: true,            renameFrom: 'ACCT_NAME_KANJI', renameConfidence: 0.85 },
      { name: 'account_name_kana',type: 'VARCHAR(80)',     nullable: true,            added: true, default: "''" },
      { name: 'risk_score',       type: 'SMALLINT',        nullable: true,            added: true, default: '0' },
      { name: 'kyc_level',        type: 'SMALLINT',        nullable: false,           added: true, default: '0' },
      { name: 'aml_flag',         type: 'BOOLEAN',         nullable: false,           added: true, default: 'false' },
      { name: 'segment_code',     type: 'VARCHAR(8)',      nullable: true,            added: true, default: 'NULL' },
      { name: 'tenant_id',        type: 'UUID',            nullable: false,           added: true, default: "'00000000-0000-0000-0000-000000000001'" },
      { name: 'updated_by',       type: 'VARCHAR(8)',      nullable: true,            renameFrom: 'UPD_USER',    renameConfidence: 0.90 },
      { name: 'updated_at',       type: 'TIMESTAMP',       nullable: true,            renameFrom: 'UPD_TS',      renameConfidence: 0.82 },
      { name: 'created_at',       type: 'TIMESTAMP',       nullable: false,           added: true, default: 'NOW()' },
    ],
  },
  {
    table: 'CUST_PROFILE',
    asis:  'CORE.CUST_PROFILE',
    tobe:  'public.CUST_PROFILE',
    asisCols: [
      { name: 'CUST_ID',      type: 'CHAR(10)',   nullable: false, pk: true },
      { name: 'NAME_KANJI',   type: 'CHAR(60) EBCDIC-KANA', nullable: false },
      { name: 'NAME_KANA',    type: 'CHAR(60) EBCDIC-KANA', nullable: false },
      { name: 'BIRTH_DT',     type: 'CHAR(8) YYYYMMDD',     nullable: true },
      { name: 'GENDER_CD',    type: 'CHAR(1)',              nullable: true },
      { name: 'NATIONALITY',  type: 'CHAR(3)',              nullable: true },
      { name: 'OPEN_BR',      type: 'CHAR(4)',              nullable: false },
      { name: 'TEL_NO',       type: 'CHAR(15)',             nullable: true },
      { name: 'LEGACY_GRADE', type: 'CHAR(1)',              nullable: true },
    ],
    tobeCols: [
      { name: 'CUST_ID',      type: 'CHAR(10)',    nullable: false, pk: true },
      { name: 'NAME_KANJI',   type: 'VARCHAR(120)',nullable: false },
      { name: 'NAME_KANA',    type: 'VARCHAR(120)',nullable: false },
      { name: 'BIRTH_DT',     type: 'DATE',        nullable: true,            renameFrom: 'BIRTH_DT',    renameConfidence: 0.82 },
      { name: 'GENDER',       type: 'VARCHAR(16)', nullable: true,            renameFrom: 'GENDER_CD',   renameConfidence: 0.72 },
      { name: 'NATIONALITY',  type: 'CHAR(3)',     nullable: true },
      { name: 'OPEN_BR',      type: 'CHAR(4)',     nullable: false },
      { name: 'PHONE_E164',   type: 'VARCHAR(20)', nullable: true,            renameFrom: 'TEL_NO',      renameConfidence: 0.55 },
      { name: 'EMAIL',        type: 'VARCHAR(255)',nullable: true,            added: true, default: 'NULL' },
      { name: 'MKT_OPT_IN',   type: 'BOOLEAN',     nullable: false,           added: true, default: 'false' },
      { name: 'RISK_TIER',    type: 'SMALLINT',    nullable: false,           added: true, default: '3' },
      { name: 'CREATED_AT',   type: 'TIMESTAMP',   nullable: false,           added: true, default: 'NOW()' },
      { name: 'UPDATED_AT',   type: 'TIMESTAMP',   nullable: false,           added: true, default: 'NOW()' },
    ],
  },
  {
    table: 'TXN_JOURNAL_2024',
    asis:  'CORE.TXN_JOURNAL_2024',
    tobe:  'public.transaction_2024',
    asisCols: [
      { name: 'TXN_ID',       type: 'CHAR(24)',         nullable: false, pk: true },
      { name: 'ACCT_NO',      type: 'CHAR(16)',         nullable: false },
      { name: 'TXN_DT',       type: 'CHAR(8) YYYYMMDD', nullable: false },
      { name: 'TXN_TM',       type: 'CHAR(6) HHMMSS',   nullable: false },
      { name: 'AMT',          type: 'COMP-3 S9(13)V99', nullable: false },
      { name: 'DR_CR',        type: 'CHAR(1)',          nullable: false },
      { name: 'BR_CODE',      type: 'CHAR(4)',          nullable: false },
      { name: 'CHANNEL_CD',   type: 'CHAR(2)',          nullable: false },
      { name: 'MEMO',         type: 'CHAR(40) EBCDIC-KANA', nullable: true },
    ],
    tobeCols: [
      { name: 'transaction_id',  type: 'VARCHAR(24)',   nullable: false, pk: true, renameFrom: 'TXN_ID', renameConfidence: 1.00 },
      { name: 'account_no',      type: 'VARCHAR(16)',   nullable: false,           renameFrom: 'ACCT_NO', renameConfidence: 1.00 },
      { name: 'occurred_at',     type: 'TIMESTAMP',     nullable: false,           added: true, default: 'NOW()', mergedFrom: ['TXN_DT','TXN_TM'] },
      { name: 'amount',          type: 'NUMERIC(15,2)', nullable: false,           renameFrom: 'AMT', renameConfidence: 1.00 },
      { name: 'direction',       type: 'VARCHAR(6)',    nullable: false,           renameFrom: 'DR_CR', renameConfidence: 0.65 },
      { name: 'branch_code',     type: 'CHAR(4)',       nullable: false,           renameFrom: 'BR_CODE', renameConfidence: 0.95 },
      { name: 'channel',         type: 'VARCHAR(16)',   nullable: false,           renameFrom: 'CHANNEL_CD', renameConfidence: 0.80 },
      { name: 'memo',            type: 'VARCHAR(80)',   nullable: true,            renameFrom: 'MEMO', renameConfidence: 1.00 },
      { name: 'reference_id',    type: 'VARCHAR(40)',   nullable: true,            added: true, default: 'NULL' },
      { name: 'currency_code',   type: 'CHAR(3)',       nullable: false,           added: true, default: "'JPY'" },
      { name: 'reversal_of',     type: 'VARCHAR(24)',   nullable: true,            added: true, default: 'NULL' },
      { name: 'created_at',      type: 'TIMESTAMP',     nullable: false,           added: true, default: 'NOW()' },
    ],
  },
];

Object.assign(window, { PROJECTS, TABLES, MAPPING, STAGES, LOG_LINES, SCHEMA_DIFF, TENANT });
